version: "3.6"

services:
  django:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: "postgres:13"
    env_file:
      - .db.env
    volumes:
      - db-volume:/var/lib/postgresql/data:rw

volumes:
  db-volume:
