version: "3.6"

services:
  django:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done   && python loans_site/manage.py migrate  && python loans_site/manage.py initadmin  && python loans_site/manage.py runserver 0.0.0.0:8000 --noreload'
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: "postgres:13"
    env_file:
      - .db.env
    volumes:
      - db-volume:/var/lib/postgresql/data:rw

volumes:
  db-volume:
