# Generated by Django 3.2.7 on 2021-09-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansrequest', '0002_auto_20210918_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dni',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
