# Generated by Django 3.2.7 on 2021-09-20 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loansrequest', '0004_auto_20210918_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
