# Generated by Django 3.2.7 on 2021-09-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansrequest', '0005_loan_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='aprobado',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='nombre',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='genero',
        ),
        migrations.AddField(
            model_name='loan',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other')], default='O', max_length=2),
            preserve_default=False,
        ),
    ]
